env:
  es6: true
  node: true
parserOptions:
  sourceType: module
  ecmaFeatures:
    spread: true
    experimentalObjectRestSpread: true
extends: eslint:recommended
rules:
  no-console: 0
  semi:
    - 2
    - never
  max-len:
    - 2
    - ignoreComments: true
