extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"

parser: "@typescript-eslint/parser"
parserOptions:
  project: "tsconfig.json"
plugins:
  - "@typescript-eslint"
rules:
  "no-unused-vars": off # see @typescript-eslint/no-unused-vars below
  "quotes":
    - error
    - double
    - allowTemplateLiterals: false
      avoidEscape: true

  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/no-floating-promises": error
  "@typescript-eslint/no-unused-vars":
    - off # replaced with tsconfig.noUnusedLocals for now
    - ignoreRestSiblings: true
  "@typescript-eslint/no-base-to-string": error
  "@typescript-eslint/restrict-template-expressions":
    - error
    - allowNumber: true
      allowBoolean: true
  "@typescript-eslint/strict-boolean-expressions":
    - error
    - allowNullableBoolean: true
      allowNullableString: true

  # "import/no-unresolved": off
  # "import/order":
  #   - error
  #   - groups:
  #       - [builtin, external]
  #       - internal
  #       - [parent, sibling, index]
  #       - type
  #       - object
  #     newlines-between: always
  #     alphabetize:
  #       order: asc
  #       caseInsensitive: true
  # "import/extensions":
  #   - error
  #   - always
