version: '3'
services:
  blcklstbot:
    build: ./
    image: kraftwerk28/blcklstbot
    environment:
      NODE_ENV: 'production'
    env_file: .env.prod
    # env_file: .env
    ports:
      - 1490:1490
    restart: always
    # network_mode: host
    depends_on:
      - redis
  redis:
    image: redis:alpine

networks:
  default:
    external:
      name: globalpg
