version: '3'
services:
  blcklstbot:
    build: ./
    # image: kraftwerk28/blcklstbot
    environment:
      NODE_ENV: 'development'
    env_file: ./.env
    ports:
      - 1490:1490
    restart: always
    # network_mode: host

networks:
  default:
    external:
      name: globalpg
