version: '3'
services:
  blcklstbot:
    build: ./
    image: kraftwerk28/blcklstbot
    environment:
      NODE_ENV: 'production'
      # NODE_ENV: 'development'
    env_file: .env.prod
    # env_file: .env.local-compose
    ports:
      - 1490:1490
    depends_on:
      - redis
    restart: "unless-stopped"
    command: [ node, index.js ]

  redis:
    image: redis:alpine
    restart: "unless-stopped"

  enry-server:
    image: kraftwerk28/enry-server
    restart: "unless-stopped"

networks:
  default:
    name: globalpg
    external: true
