version: '3'
services:
  blcklstbot:
    build: ./
    environment:
      NODE_ENV: 'production'
    env_file: ./.env.prod
    ports:
      - 1490:1490
    restart: always

networks:
  default:
    external:
      name: globalpg
